### ISSUE TITLE
Request error when running demo.py

### ISSUE THREAD

**Issue by WinstonDeng** [facebookresearch/c3dpo_nrsfm#1]
Error info:

> requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8097): Max retries exceeded with url: /events (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002413CA92E10>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',))

**Comment by davnov134** [comment]
Hi, please make sure to start the visdom server before running the code. This can be done by running:
> python -m visdom.server
from a different terminal window that the one you used for launching the demo.py.

In any case, although the error appears, the script should still continue without any issues (except that you won't see any visualizations in visdom).

**Comment by WinstonDeng** [comment]
Thanks a lot!
