### ISSUE TITLE
No output when implementing evaluate.py

### ISSUE THREAD

**Issue by MritulaC** [facebookresearch/c3dpo_nrsfm#10]
Hi,
 I am trying to implement c3dpo_nrsfm as in github to learn it. I am neither getting any extracted 3D points nor an error. It stays as below
![image](https://user-images.githubusercontent.com/10527105/73754009-94119e00-475b-11ea-8209-e5424386dad2.png)
 
I tried the following commands in the sequence

1.   python -m visdom.server
2.   python ./experiment.py --cfg_file ./cfgs/h36m.yaml  

and 

1.   python -m visdom.server
2.   python ./demo.py

thanks
Mritula

**Comment by davnov134** [comment]
Hi Mritula,

It seems that you are using windows which might be a reason why the method is failing.

Can you please identify the line of code where it hangs?

Thanks
David

**Comment by MritulaC** [comment]
Hi, I tried from initial steps, this time I managed installing torch 1.1.0, and re-running demo.py. I am getting a stick figure display now. 

Previously, I used the latest torch version, unsure if this would have made all the difference.

Thanks
Mritula
