### ISSUE TITLE
human scale

### ISSUE THREAD

**Issue by xjturobocon** [facebookresearch/c3dpo_nrsfm#11]
Hey, it seems that you assumed the scale of the person is known, so if we run the model on a new dataset, and don't have human scale, we can not predict absolute 3d keypoints coordinates, right?

**Comment by davnov134** [comment]
Hi, I would not say that the network needs to know the scale of any object it reconstructs. It is true that the size of reconstructions is in world units that do not correspond to existing metric units. Otherwise any information about object size is not needed for successful convergence.
