### ISSUE TITLE
How to train a model for coco human dataset?

### ISSUE THREAD

**Issue by WinstonDeng** [facebookresearch/c3dpo_nrsfm#3]
I'm trying to train a model for coco human dataset.  However, there is no coco url in **DATASET_URL**. What should I do?

**Comment by davnov134** [comment]
Hi, please follow these steps:
(1) convert coco keypoints to a .json file, following the format of the other dataset files
(2) copy-paste the ./cfgs/h36m.yaml file and name it ./cfgs/coco.yaml
(3)  in ./cfgs/coco.yaml change the MODEL.n_keypoints to match the number of keypoints in coco
(4) in ./cfgs/coco.yaml change the name of the dataset to match your new coco .json file
(5) launch training

**Comment by WinstonDeng** [comment]
Thanks for your help!

**Comment by MritulaC** [comment]
What is the format of the input .json file?

**Comment by davnov134** [comment]
Please refer to the documentation of class `KeypointsDataset` in `dataset/keypoints_dataset.py` for the description.
