### ISSUE TITLE
Train custom dataset

### ISSUE THREAD

**Issue by spgitmonish** [facebookresearch/c3dpo_nrsfm#4]
How do I train this model on a custom dataset? What are the steps I need to follow?

**Comment by WinstonDeng** [comment]
Same issue I posted has been closed.
check here:
[https://github.com/facebookresearch/c3dpo_nrsfm/issues/3](url)

**Comment by davnov134** [comment]
Many thanks for posting the link to the closed issue -> closing this issue as well.
