### ISSUE TITLE
kp_loc and kp_original

### ISSUE THREAD

**Issue by sjtuxcx** [facebookresearch/c3dpo_nrsfm#6]
Hi, I notice you have normalized the original 2D keypoint coordinate to kp_loc in the dataset file, but how do you normalize it? Thanks!

**Comment by davnov134** [comment]
Hi, we follow the same protocol as in Kudo et al: Unsupervised Adversarial Learning of 3D Human Pose from 2D Joint Locations.

For the exact normalization procedure, please refer to:
https://github.com/DwangoMediaVillage/3dpose_gan/blob/master/projection_gan/pose/dataset/pose_dataset.py
