### ISSUE TITLE
Visdom of demo program

### ISSUE THREAD

**Issue by Vandejun** [facebookresearch/c3dpo_nrsfm#8]
Hello, we are very interested in your research, but we need to download the sample file from visdom to run the program. Due to the limitation of Chinese network, visdom cannot be installed and used normally. Can you provide the static folder of visdom for us to manually replace the static file in the visdom directory. Thanks.

**Comment by davnov134** [comment]
Hi, the script `demo.py` also contains matplotlib visualisations that do not require a visdom server. You can use those to visualize the results.

Please not that Visdom is not a hard requirement of the method, you can simply skip the visualisation steps in the code and everything should run fine.
