### ISSUE TITLE
Applying to other dataset

### ISSUE THREAD

**Issue by MritulaC** [facebookresearch/c3dpo_nrsfm#9]
Hi,
 I have several images of humans in .jpg format. I am trying to extract 3D poses from these images.  How am I to apply c3dpo_nrsfm to my input images? 

Thanks
Mritula

**Comment by davnov134** [comment]
Hi, you would have to first extract 2D human keypoints from the images and run the method on those.

You can use e.g. the stacked hourglass detector for extracting the 2D human keypoints from a big dataset of images with humans. Given those keypoints you can then train c3dpo and later use it at test time to lift the 2D keypoint detections to 3D.

**Comment by MritulaC** [comment]
Hi Thanks for your reply. Yes, I have the 2D keypoints in .json format, further, how should I send them as inputs?

Thanks
Mritula

**Comment by Mik1337** [comment]
Substitute your 2D keypoints in the dataset_configs.py under the connectivity patterns and should be able to run the demo script and get your 3D Pose estimate.
